[project]
name = "bankparse"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pandas>=2.3.3",
    "pdfplumber>=0.11.9",
    "typing>=3.10.0.0",
    "unidecode>=1.4.0",
]
